### ISSUE TITLE
Bug Round traitor +detective 

### ISSUE THREAD

**Issue by Kerimengit** [nushnush/TF2-Trouble-In-Terrorist-Town#1]
Hello, forgive me for my English, I'm from Russia and decided to test your plugin on my server and found a bug, there is a problem when a traitor kills all civilians, his victory is not protected. There is one more bug when a person becomes a detective in the chat he writes that he is a traitor

**Comment by Almoger** [comment]
Huge thanks for submitting a reply, I'll check those issues and notify on the AlliedModders thread when I finish the updates.

**Comment by Kerimengit** [comment]
> Огромное спасибо за отправку ответа, я проверю эти проблемы и уведомлю об этом в потоке AlliedModders, когда закончу обновления.

I want to say right away that the problem with the victory of the pretadels does not happen immediately, but after 3-4 rounds, and it also happens with peaceful

**Comment by Almoger** [comment]
Hopefully, this should be fixed now [in here](https://github.com/nushnush/TF2-Trouble-In-Terrorist-Town/releases/tag/v0.1.1). If you encounter these issues again, please open another issue.
