### ISSUE TITLE
Bug checking player via reload button

### ISSUE THREAD

**Issue by Kerimengit** [nushnush/TF2-Trouble-In-Terrorist-Town#4]
I noticed the problem that you can inspect the corpse being very far from it, and you can use this bug for the traitor when you buy an explosive corpse in the shops, kill and look at it with a sight, and from a distance you click on reload and the corpse explodes, and just like with ordinary corpses. I will attach a screenshot on it I am far from the body
![unknown](https://user-images.githubusercontent.com/75506744/101261203-80054700-3746-11eb-8a07-2739e2687fd3.png)

**Comment by Kerimengit** [comment]
also the players noticed if you kill a traitor for a peaceful one, your karma decreases

**Comment by Kerimengit** [comment]
and another problem is that if you change the cvar on the server, the plugin automatically sets the cvar that is specified in the code

**Comment by Kerimengit** [comment]
There is also a problem in the disappearance of the weapon interface after several rounds

**Comment by Almoger** [comment]
- Inspecting the body from far away is not a bug, but I'll definitely block this feature. 
- The issue with the cvars not being updated: they actually are, only the timer is not being updated. I'm afraid that can't be changed cause the timer's cvars must apply exactly when setup time begins, or else the timer will break.
- Regarding the others, I'm not really sure what you're talking about. Please create another issue with more description of those.
