### ISSUE TITLE
Connect server player bug

### ISSUE THREAD

**Issue by Kerimengit** [nushnush/TF2-Trouble-In-Terrorist-Town#5]
When a player is connected to the server, the player does not throw into the team in a new round, he simply remains an observer and it is not possible to choose a team, well, it shows that he is in the team on scorebouards and even chooses him as a traitor or a detective and no matter how many rounds he is past throws into the team and even restarting the server does not help

**Comment by Almoger** [comment]
Should be fixed in the new release
