### ISSUE TITLE
Create new roles

### ISSUE THREAD

**Issue by Almoger** [nushnush/TF2-Trouble-In-Terrorist-Town#6]
1.  **_Disguiser_**:  
* When he kills, he gets the cosmetics of his victim.
2. **_Necromancer_**: 
* When alive, can cause earthquakes that will shake players' screens.
* When he dies, he can press E to respawn him or one of his fellows.
3. **_Pestilence_**:  
* Touch players to spread your disease. 
* Dying will remove the disease from all the infected players.

~~4. **_Dark Knight_**:~~
~~* Aim at players and press MOUSE2 to drain their health.~~
~~* While draining health, you grow bigger and increase your max health.~~
~~* While draining health, you and your target are frozen.~~

**Comment by nushnush** [comment]
> **_Disguiser_**:
When he kills, he gets the cosmetics of his victim.

Currently done

**Comment by Almoger** [comment]
All done
